
export const ADD_TODO="ADD_TODO";
export const UPDATE_TODO="UPDATE_TODO";
export const DELETE_TODO="DELETE_TODO"
export const FILTER_TODOS="FILTER_TODOS";
export const SET_FILTER="SET_FILTER";
export const FETCH_TODOS_SUCCESS='FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAILURE='FETCH_TODOS_FAILURE';
export const ADD_TODO_SUCCESS='ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE='ADD_TODO_FAILURE';
export const UPDATE_TODO_SUCCESS='UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FAILURE='UPDATE_TODO_FAILURE';
export const DELETED_TODO_SUCCESS='UPDATE_TODO_SUCCESS';
export const DELETED_TODO_FAILURE='UPDATE_TODO_FAILURE';

